# Generated by Django 4.2.1 on 2023-11-23 06:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("emp_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="permission",
        ),
        migrations.DeleteModel(
            name="Permission",
        ),
    ]
